### PR TITLE
Bugfix: modal wobble on transition in/out

### LINKED ISSUE #1870: Modal height (h-fit / h-full)
### Describe the feature in detail (code, mocks, or screenshots encouraged)

As discussed in Discord we need a way to make the user decide if they want `h-fit` or `h-full`.

## Potential solutions
1. provide a `CssClass` prop `height` with a default value and document both possibilities with their side effects.
2. provide an enum sort of prop that lets the user choose one of both solutions.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

Discord support issue -> https://discord.com/channels/1003691521280856084/1140610247304679454

last PR targeting this issue (changed from h-full to h-fit) -> #1695 

issue (caused by h-full) -> #1683

### LINKED ISSUE #2239: Modal sliding to the right while opening
### Current Behavior

With a basic modal component in use I am seeing the modal slide to the right by about 5px while opening. 

### Expected Behavior

When the modal opens it should transition in, but not slide to the right after it displays. 

### Steps To Reproduce

1. Open the stackblitz below
2. Click the "Open Modal" button
3. Watch the modal open and slide to the right as it becomes visible

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/skeletonlabs-repl-g8eubt

### More Information

_No response_

### PR DESCRIPTION
**Pull request by Mahmoud-zino**
## Linked Issue

Closes #2239
Closes #1870

## Description

Fixed the issue by checking the client height and comparing it to the window height and then adding the overflow based on the result.

> Note: `cOverflow` is added directly to the classes of the `backdrop` because otherwise the reactivity won't be triggered on every change.

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by Mahmoud-zino** [comment]
@endigo9740 this won't solve #1870, but I though separating them will simplify the review.
If this solution is accepted we can close #2241 . Thank you @CoreyT355 for helping with this bug.

**Comment by CoreyT355** [comment]
> @endigo9740 this won't solve #1870, but I though separating them will simplify the review. If this solution is accepted we can close #2241 . Thank you @CoreyT355 for helping with this bug.

@Mahmoud-zino That's a nice solution. I haven't worked with the `svelte:window` piece yet, so I didn't think about it when the idea of catching the window height came up. 
Thanks for finding a solution here. Hopefully this gets merged in.

**Comment by endigo9740** [comment]
@CoreyT355 @Mahmoud-zino I've been handling PR reviews on Sunday's (tomorrow for me) so expect a proper audit then.

File: packages/skeleton/src/lib/utilities/Modal/Modal.svelte [hunk 1]
```diff
@@ -115,6 +115,9 @@
 	};
 	let currentComponent: ModalComponent | undefined;
 	let registeredInteractionWithBackdrop = false;
+	let modalElement: HTMLDivElement;
+	let windowHeight: number;
+	let cBackdropOverflow: CssClasses = 'overflow-y-hidden';
```
Comment (endigo9740) [inline packages/skeleton/src/lib/utilities/Modal/Modal.svelte:120]: The `cX` classes are meant to be a fixed set of base classes that do not change. To avoid confusion, I'd rename and drop the "c". Likewise remove the CssClasses type designation - those are only needed for exposed props that users can override. It's an identifier that enables Tailwind Intellesense for those props. Given it's a privative, you can leave off the type entirely in fact!

File: packages/skeleton/src/lib/utilities/Modal/Modal.svelte [hunk 2]
```diff
@@ -131,6 +134,19 @@
...
+		if (!modalHeight) return;
+
+		if (modalHeight > windowHeight) {
+			cBackdropOverflow = 'overflow-y-auto';
+		} else {
+			cBackdropOverflow = 'overflow-y-hidden';
+		}
+	}
+	// first child of the modal is the content.
+	$: onModalHeightChange((modalElement?.firstChild as HTMLElement)?.clientHeight);
```
Comment (endigo9740) [inline packages/skeleton/src/lib/utilities/Modal/Modal.svelte:148]: I'm not sure `firstChild` is reliable here. While we suggest users created their custom modal components with a single wrapping element, there's no guarantee they will. Any reason not to just verify the size of the modal element itself? It should always be present and always wrap the entirety of the content.

If you're concerned about padding and borders - then I'd recommend the use of `offsetHeight`:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight

**Comment by endigo9740** [comment]
@Mahmoud-zino just a couple small nitpicks here, but overall I like this. It seems to be a great solution to the issue at hand.

File: packages/skeleton/src/lib/utilities/Modal/Modal.svelte [hunk 3]
```diff
@@ -101,7 +101,7 @@
 	export let transitionOutParams: TransitionParams<TransitionOut> = { duration: 150, opacity: 0, x: 0, y: 100 };
 
 	// Base Styles
-	const cBackdrop = 'fixed top-0 left-0 right-0 bottom-0 overflow-y-auto';
+	const cBackdrop = 'fixed top-0 left-0 right-0 bottom-0';
 	const cTransitionLayer = 'w-full h-fit min-h-full p-4 overflow-y-auto flex justify-center';
```
Comment (endigo9740) [inline packages/skeleton/src/lib/utilities/Modal/Modal.svelte:105]: Per my comment in #2241, I'd recommend appending testing with `max-h-screen` applied to the `cTransitionLayer` classes. Though off hand it seems redundant with `w-full`. I'm sure there's a good reason for this that's not obvious to me though.

File: packages/skeleton/src/lib/utilities/Modal/Modal.svelte (hunk 2 above)
Comment (Mahmoud-zino) [reply packages/skeleton/src/lib/utilities/Modal/Modal.svelte]: @endigo9740 
while you are correct about the `firstChild` not being reliable, the modal element itself is also not reliable, when using custom modals the modal-element has the height of (0) always. so I have changed the code to check both the parent and the child before deciding which one represents the size. this should work with every situation.

File: packages/skeleton/src/lib/utilities/Modal/Modal.svelte (hunk 3 above)
Comment (Mahmoud-zino) [reply packages/skeleton/src/lib/utilities/Modal/Modal.svelte]: @endigo9740 I also don't know why it is important  😄, but I have added it 👍

**Comment by Mahmoud-zino** [comment]
@endigo9740 I just checked it again, this is the effect of having `max-h-screen`, deleting it solved the issue.

**Comment by endigo9740** [comment]
@Mahmoud-zino That's awesome. In order to properly test this, can you do me a favor and implement a new component modal example that is full screen? Just follow the lead of the current examples. Without that we don't have a great way to test all three conditions I mentioned above. The contents of the modal can be anything - even just placeholder text that says: "Full Screen Example". I'll polish it a bit more later.

**Comment by endigo9740** [comment]
@Mahmoud-zino I've moved, renamed, and updated the Modal docs to showcase the new "full" modal option. I've also update the contents of the modal to provide some simpler styles for showcasing how this can work.

Note there is currently no way to disable the backdrop > modal-transition built in padding. But I think that's an issue we should address in Skeleton v3.

I also see how you're handling modals that are oversized vertically. The scrollbar won't appear as you resize your window, but will appear if that size is too large when the modal appears. I think that's a happy medium for now. Again, I'd like to tackle the root issues for this in v3.

Assuming you're happy with my changes, feel free to approve this PR and I'll aim to merge right away. Thanks for the hard work on this one!

**Review by endigo9740 — APPROVED** [review]

**Comment by Mahmoud-zino** [comment]
@endigo9740 I can't approve my own PR, but it looks good to me :+1:
