### PR TITLE
Only render `<button>` when trigger is present

### LINKED ISSUE #2944: Hidding Modal trigger button leaves an invisible button in markup
### Current Behavior

When not providing a `{#snippet trigger()}` there is an invisible button left in the markup

### Expected Behavior

There shouldn't be a button left in the markup if no `{#snippet trigger()}` is provided

### Steps To Reproduce

```svelte
<Modal
    bind:open={modalOpen}
    contentBase="card bg-surface-400-600 p-4 space-y-4 shadow-xl max-w-screen-sm"
    backdropClasses="backdrop-blur-sm"
>
    {#snippet content()}
       Some content.....
    {/snippet}
</Modal>
```
### Link to Reproduction / Stackblitz

_No response_

### More Information

https://discord.com/channels/1003691521280856084/1191790107867488316/1305590564497920010

### PR DESCRIPTION
**Pull request by Hugos68**
## Linked Issue

Closes #2944

## Description

Adds an `if` statement around the button to only render it if the snippet is actually passed, this was previously posing an a11y hazard.

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by Hugos68** [comment]
@endigo9740 What is the `span` doing? I'm in favor of removing that, unless you added that for a specific reason.

File: packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte [hunk 1]
```diff
@@ -60,10 +60,12 @@
 </script>
 
 <span>
-	<!-- Trigger -->
-	<button {...api.getTriggerProps()} class="{triggerBase} {triggerBackground} {triggerClasses}">
-		{@render trigger?.()}
-	</button>
+	{#if trigger}
+		<!-- Trigger -->
```
Comment (endigo9740) [inline packages/skeleton-svelte/src/lib/components/Modal/Modal.svelte:64]: Super uber nitpick - move the comment above the `#if` statement please!

**Review by endigo9740 — CHANGES_REQUESTED** [review]
I'll do a follow up review once I can once again start the `skeleton-svelte` dev server.

**Comment by endigo9740** [comment]
> @endigo9740 What is the `span` doing? I'm in favor of removing that, unless you added that for a specific reason.

This prevents the trigger/popup from being affected by the flow of styles. So if you do something like this:

```
<div class="flex space-y-4">
    (button)
    <Modal>
    (button)
<div>
```

We don't want the trigger/modal getting affected by the extra spacing between elements. The span isolates that so it's only affected by the positioning of the Modal logic itself (via Floating UI or w/e)
