### PR TITLE
Fix RadioGroup spacing

### LINKED ISSUE #2295: Spacing prop is ignored by RadioGroup
### Current Behavior

The RadioGroup component accepts a "spacing" prop that is supposed to override the default spacing. However the spacing relevant code in RadioGroup is as follows:
```
<script>
export let spacing = "";
//...
$:
  spacing = `${display.includes("flex-col") ? "" : "space-x-1"}`;
$:
  classesBase = `${cBase} ${display} ${background} ${border} ${spacing} ${rounded} ${$$props.class ?? ""}`;
</script>

<div class="radio-group {classesBase}" data-testid="radio-group" role="radiogroup" aria-labelledby={labelledby}>
    <slot />
</div>
```

This prevents the spacing prop being considered as the reactive line will always default spacing to "" or "space-x-1"

### Expected Behavior

Spacing prop should effect the css classes.

### Steps To Reproduce

Use spacing on RadioGroup component

### Link to Reproduction / Stackblitz

https://stackblitz.com/edit/jq-starter-zrlfgn?file=my-skeleton-app%2Fsrc%2Froutes%2F%2Bpage.svelte

### More Information

_No response_

### PR DESCRIPTION
**Pull request by phamduylong**
## Linked Issue

Closes #2295

## Description

Made spacing props to adopt value passed in and set *space-x-1* as default value for it

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

File: packages/skeleton/src/lib/components/Radio/RadioGroup.svelte [hunk 1]
```diff
@@ -47,8 +47,6 @@
 	const cBase = 'p-1';
 
 	// Reactive
-	// display space-x only on row flex as it is not needed on column flex.
-	$: spacing = `${display.includes('flex-col') ? '' : 'space-x-1'}`;
```
Comment (Mahmoud-zino) [inline packages/skeleton/src/lib/components/Radio/RadioGroup.svelte:51]: @phamduylong we still need this because of this bug: #1672
I would suggest the following:
```ts
export let spacing: CssClasses = 'space-x-1';
//....
// display space-x only on row flex as it is not needed on column flex.
$: classesSpacing = `${display.includes('flex-col') ? '' : spacing}`;
$: classesBase = `${cBase} ${display} ${background} ${border} ${classesSpacing} ${rounded} ${$$props.class ?? ''}`;
```

**Review by Mahmoud-zino — CHANGES_REQUESTED** [review]

**Comment by endigo9740** [comment]
@phamduylong @Mahmoud-zino so we had two issues here, neither of which would be solved by adding a `spacing` prop:

1. `display` was not the appropriate prop to add `flex-col` for vertical layouts.
2. `gap` is the appropriate style/prop to handle both vertical and horizontal gap spacing.

To correct this I've made a few changes:

1. `display` is now properly labeled to handle `display: x` CSS styles
2. A new `flexDirection` prop has been added to handle `flex-col` classes
3. A new `gap` prop has been added to handle universal item spacing (vertical/horizontal)
4. The docs have been updated to denote all changes.

This should provide a much more better solution to the original issue, while fixing the misuse of the `display` property.

**Comment by Mahmoud-zino** [comment]
@endigo9740 your solution with the ` gap` prop  is great! but are we ok with having duplicated ` inline-flex`  classes? 
it won't have an effect but it doesn't look clean!

**Comment by endigo9740** [comment]
This `flexDirection` prop had an incorrect default value. It should now be set to `flex-row` on the `dev` branch. Thanks for the catch @Mahmoud-zino
