### PR TITLE
breaking: Refactor global stores for `Modal`, `Toast`, and `Drawer`

### LINKED ISSUE #522: Unsafe store behaviour of utility components in SvelteKit
### Current Behavior

Currently components like Toast use [exported const stores ](https://github.com/Brain-Bones/skeleton/blob/dev/src/lib/utilities/Toast/stores.ts#L47) to function. This is completely fine for all uses cases outside of SvelteKit, as any const variable imported from a library will become global/shared state between requests. This could and will cause unintended behaviour when using SvelteKit. 
I haven't spent time to properly test what the impact would be in skeleton's case, so I don't know what would break. 

Potential solutions were discussed in discord, also the way Drawers are written should mean that they are safe to use, it looks like only Dialog and Toast are affected.

### Steps To Reproduce

Import any const store in sveltekit with SSR enabled.

### Anything else?

[Dicussion about shared state/stores and SvelteKIt](https://github.com/sveltejs/kit/discussions/4339#discussioncomment-2384978) 
[Issue about shared state behaviour](https://github.com/sveltejs/kit/issues/1542)
[Another related issue](https://github.com/sveltejs/kit/issues/2213)

### PR DESCRIPTION
**Pull request by AdrianGonz97**
## Linked Issue

Closes #522 

## Description

This PR aims to fix the SSR related issues that comes with stores that are defined in the global scope. To fix this, we'll be using Svelte's context API as a means of attaching these stores to the component tree for safe keeping.

### Store Initialization
The first change is how these utility stores are initialized. As we are using contexts now, we need to initialize and set the contexts for these stores in the root layout file. 

We provide a utility function, `initializeStores()`, that will handle the initialization for the users:
```svelte
<!-- src/routes/+layout.svelte -->
<script lang="ts">
	import { Toast, Modal, Drawer, initializeStores } from "@skeletonlabs/skeleton";
	
	initializeStores();
</script>

<Toast />
<Modal />
<Drawer />
```

### Retrieving Stores
Stores for `Modal`, `Toast`, and `Drawer` are now accessed through a function that will retrieve their respective stores.

```ts
import { getToastStore, getDrawerStore, getModalStore } from "@skeletonlabs/skeleton";

const toastStore = getToastStore();
const drawerStore = getDrawerStore();
const modalStore = getModalStore();
```

...and that's it! It's a pretty minor, yet effective change that clears up all of the nasty SSR issues that these particular stores have been troubling us with.

As a bonus, these stores can now be safely used at the top level of components without any fear of the server's store persisting its state:
```svelte
<script lang="ts">
	import { toastStore } from '@skeletonlabs/skeleton';

	toastStore.trigger({
		message: 'Howdy!',
		autohide: false
	});
</script>

<!-- ... -->
```

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
Seems good at at glance @AdrianGonz97. I'll test it out this week and we'll aim to get this in for the v2 release. Thank you for updating the docs already as well!

File: packages/skeleton/src/lib/utilities/index.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * <Modal />
+ * <Drawer />
+ * ```
+ */
+export function initializeStores() {
+	const modalStore = initializeModalStore();
+	const toastStore = initializeToastStore();
+	const drawerStore = initializeDrawerStore();
+
+	return { drawerStore, modalStore, toastStore };
```
Comment (Sarenor) [inline packages/skeleton/src/lib/utilities/index.ts:27]: Should we return these here or is that just going to lead to people using it for anti patterns like prop drill down?

Comment (AdrianGonz97) [reply packages/skeleton/src/lib/utilities/index.ts:27]: @Sarenor Fair point! I figured that there was some use case where someone would want to immediately use a store after initialization, but I'd be down to just making this return void instead.

Comment (Sarenor) [reply packages/skeleton/src/lib/utilities/index.ts:27]: I'm open to discussion, there might be a use for it as you said. Just want to avoid people thinking they have to pass it down

Comment (AdrianGonz97) [reply packages/skeleton/src/lib/utilities/index.ts]: Nah, I'm convinced. I was debating this internally anyway when I initially wrote it. Having a single interface for retrieving the stores is better and more clear to the users!

**Comment by endigo9740** [comment]
@AdrianGonz97 I always like to add context for WHY you're implementing something in the instruction, so I've modified this bit in the featured example for drawers, modals, and toasts:

Screenshot 2023-08-09 at 12 52 02 PM

I think with this I'm good with moving forward and merging this.

**Review by endigo9740 — APPROVED** [review]
