### PR TITLE
bugfix: appshell-scroll-handler

### LINKED ISSUE #1670: AppShell on:scroll={handler} gives invalid type for event
### Current Behavior

I've setup a default SkeletonUI project and want to use the on:scroll on the AppShell. But following the docs I get a warning: 
```
Argument of type '(event: UIEvent & { currentTarget: EventTarget & HTMLDivElement; }) => void' is not assignable to parameter of type '(e: Event) => void'.
  Types of parameters 'event' and 'e' are incompatible.
    Type 'Event' is not assignable to type 'UIEvent & { currentTarget: EventTarget & HTMLDivElement; }'.
      Type 'Event' is missing the following properties from type 'UIEvent': detail, view, which, initUIEvent
```

the handler looks like this: 
```
	function scrollHandler(event: UIEvent & { currentTarget: EventTarget & HTMLDivElement }) {
		$scrollY = event.currentTarget.scrollTop;
	}
```

The project compiles without error and the scrolling object that's using $scrollY from the store is working just fine. Only the IDE shows the abovementioned error. 

### Expected Behavior

the scrollHandler argument type should match the on:scroll defined type. 

### Steps To Reproduce

`<AppShell` ... on:scroll={scrollHandler}>`

`function scrollHandler(event: UIEvent & { currentTarget: EventTarget & HTMLDivElement; }) {
	console.log(event.currentTarget.scrollTop);
}`

### Link to Reproduction / Stackblitz

_No response_

### More Information

_No response_

### PR DESCRIPTION
**Pull request by Mahmoud-zino**
## Linked Issue

Closes #1670

## Description

Applied changes suggested by @AdrianGonz97 in https://github.com/skeletonlabs/skeleton/issues/1670#issuecomment-1615209699

## Changsets

bugfix: fixed `scroll` event type in `AppShell`

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

File: packages/skeleton/src/lib/components/AppShell/AppShell.svelte [hunk 1]
```diff
@@ -9,7 +9,11 @@
 	 */
 
 	// Types
-	import type { CssClasses } from '../../index.js';
+	import type { CssClasses, SvelteEvent } from '../../index.js';
+
+	interface $$Events {
+		scroll: SvelteEvent<Event, HTMLDivElement>;
```
Comment (AdrianGonz97) [inline packages/skeleton/src/lib/components/AppShell/AppShell.svelte:15]: It's better to define the event type for what it is, rather than a generic Event
```suggestion
		scroll: SvelteEvent<UIEvent, HTMLDivElement>;
```

Comment (Mahmoud-zino) [reply packages/skeleton/src/lib/components/AppShell/AppShell.svelte]: I missed that, thanks

**Review by AdrianGonz97 — APPROVED** [review]
